### ISSUE TITLE
emu install fails with undefined symbol: Perl_Gthr_key_ptr

### ISSUE THREAD

**Issue by moltude** [moltude/emu-vagrant#1]
fails during luts dump and rebuild, when trying to start the fifo service by invoking "fifoserver":

/usr/bin/perl: symbol lookup error: /home/emu/texpress/texapi/perl/auto/ke/texapi/texapi.so: undefined symbol: Perl_Gthr_key_ptr

**Comment by moltude** [comment]
This was an issue with .profile sourced properly

**Comment by chetanpatangade** [comment]
I am getting the below error while running the perl script:-

/usr/bin/perl: symbol lookup error: /usr/local/lib64/perl5/auto/Sub/Name/Name.so: undefined symbol: Perl_Gthr_key_ptr

Can u please help me ASAP

**Comment by moltude** [comment]
I resolved by properly reloading my .profile and .local-profile settings from a shell script (source .profile instead of . ./.profile)

**Comment by chetanpatangade** [comment]
Can you please prvode me the steps to resolve it ?

**Comment by moltude** [comment]
https://github.com/moltude/emu-vagrant/blob/master/vagrant/bootstrap.sh#L116
